mongodb:
  exam-station:
    uri: 'mongodb://localhost:27017'
  exam-result:
    uri: 'mongodb://localhost:27017'
  account-center:
    uri: 'mongodb://localhost:27017'

custom:
  credit-ease:
    sign-key: '96388dd2f29d13370b9a3cb488cbe128acd6c70b45e527ca185423b4972600c4'
    client-id: '5f3a1d4babebfe757b27bdcf'
    client-secret: 'crvtEXG1mDac4fajyfoWMow57Lq2O8NTrL6mHSjk9iP7MDPnhCebCOJ2PDPuZfXB'
    account-name: 'production.creditease@creditease.com'
    account-password: 'qSyPVNzl80BsKxoCR3XYZbMLt9j71Efr'
    assess-result-notify-url: "https://www.cejifenshangcheng.com/V2020api/integralmall/mallOrder/receiveAssessResult"
  baiding-school:
    client-id: '604acb33ec19891262e0656a'
    client-secret: 'iDPzXrFpHCQznDSoMrPdozljqZPlRdgKhyweDLMeIZinDdcvGqMvdHheIrIf2qu3'
    account-name: 'production.baidingschool@baidingschool.com'
    account-password: 'JavXTh46t01Z5g9zPuqr8VydsC2kKIxY'