mongodb:
  exam-station:
    uri: 'mongodb://localhost:27017'
  exam-result:
    uri: 'mongodb://localhost:27017'
  account-center:
    uri: 'mongodb://localhost:27017'

custom:
  credit-ease:
    sign-key: '7be47baf24d901787b6148d23661f7745e2ae156d00b2cab111913dd4ffe9ce1'
    client-id: '5f3a1bba2443695ab9c46755'
    client-secret: 'k4aKjkS6qRLixOZQFK4kv4bUHTi6tlrt5iDtGL5Mv5gUQELunwMq7blJXl9bucH9'
    account-name: 'integrating.creditease@creditease.com'
    account-password: 'MDcIea5CnFGKBHwJtjOTNAiobkRg1xX6'
